Added login and signup via Firebase and user gets email verification …
Carlos-Georgescu/Foundy pull request #1
Opened 2022-06-23 23:55 UTC by Carlos-Georgescu

…upon signup, user can only login once they verified email

2022-06-27 17:23 UTC, jakano commented
This is a fairly large commit. Can we split it up?

2022-06-28 17:45 UTC, jakano requested changes
Lets try to split this up some more

2022-07-06 17:18 UTC, jakano requested changes

2022-07-06 17:20 UTC, jakano requested changes

2022-07-06 17:20 UTC, jakano commented on app/src/main/java/com/example/foundy/SignUp.java
> +    private FirebaseAuth mAuth;
These should not be class scoped variables since they are only used locally in a method. These variables are also not used by any other classes.

2022-07-13 18:20 UTC, oulmachev reviewed
Overall looks good, just consider refactoring your code in `signUp.setOnClickListener` and ` mAuth.createUserWithEmailAndPassword(valEmail,valPassword).addOnCompleteListener` as mentioned in my comments.

2022-07-18 23:15 UTC, closed without merging