Upload Lost Item Screen + all the other screens
Carlos-Georgescu/Foundy pull request #3
Opened 2022-07-07 15:40 UTC by Carlos-Georgescu

2022-07-07 17:10 UTC, jakano requested changes

2022-07-07 17:10 UTC, jakano commented on app/src/main/java/com/example/foundy/Structures/LostItem.java
> +    public Uri image;
Instead of making this public, why not leave them private, but have a getter method to access the variables value.

https://www.geeksforgeeks.org/advantages-of-getter-and-setter-over-public-fields-in-java-with-examples/

2022-07-07 17:25 UTC, jakano requested changes

2022-07-07 17:25 UTC, jakano commented on app/src/main/java/com/example/foundy/uploadActivities/UploadLost.java
> +    Uri saveUriPic;
When you don't declare a scope of a variable in java, its default is protected (package private). Are you sure we want this to be the scope of the variables?

2022-07-07 17:25 UTC, jakano commented on app/src/main/java/com/example/foundy/uploadActivities/UploadLost.java
>      protected void onCreate(Bundle savedInstanceState) {
This method is far too big. We should break up its functionality into more digestable components.


Here on some tips on why and how to do this
https://ncrcoe.gitbooks.io/java-for-small-teams/content/style/300_keep_methods_small_and_simple.html

2022-07-07 17:30 UTC, jakano requested changes

2022-07-07 17:30 UTC, jakano commented on app/src/main/java/com/example/foundy/MapActivity.java
> +    MapsFragment mapsFragment;
When you don't define a scope for a variable, it's defaulted to protected (package private). Why do you want this variable to be of that scope?

2022-07-07 17:43 UTC, jakano requested changes
this commit is also far too big. We should break it up as was done before.

2022-07-07 17:43 UTC, jakano commented on app/src/main/java/com/example/foundy/LoginActivity.java
> +
Why are these class variables if they are only used within a single function?

2022-07-07 17:48 UTC, jakano commented on app/src/main/java/com/example/foundy/MainActivity.java
> +
Why are these class member variables (global scoped) if they are only used locally within a single method?

2022-07-07 17:49 UTC, jakano commented on app/src/main/java/com/example/foundy/SlideLayoutAdapter.java
> +    LayoutInflater layoutInflater;
When you don't define variable scope, its default is protected (package private). are you sure this is the scope you want for these variables? If so, why?

2022-07-07 17:50 UTC, jakano commented on app/src/main/res/layout/activity_slide_layout.xml
> +        android:layout_marginEnd="30dp"
Are you sure you don't want to use a dimens value for this?

2022-07-08 22:23 UTC, merged

2022-07-08 23:57 UTC, Carlos-Georgescu commented on app/src/main/java/com/example/foundy/Structures/LostItem.java
> +    public Uri image;
changed